import Vuex from "vuex";
import Vue from "vue";

Vue.use(Vuex)

export default new Vuex.Store({
    state:{
        blogPosts: [{"title":"Stringtough","content":"Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.","id":"08154f50-f79d-446f-9c7e-f2b4a86126cb","author":"Quentin","timestamp":"1:50 PM","imageUrl":"http://dummyimage.com/175x236.jpg/5fa2dd/ffffff"},
        {"title":"Job","content":"Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.","id":"efa5aeb2-167c-404a-a31b-6762c94eeea6","author":"Erich","timestamp":"12:08 PM","imageUrl":"http://dummyimage.com/169x104.bmp/5fa2dd/ffffff"},
        {"title":"Ventosanzap","content":"Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.","id":"c49ea4b7-1e5c-484e-88b5-522a7bf1ccc7","author":"Eleanore","timestamp":"10:05 PM","imageUrl":"http://dummyimage.com/184x238.jpg/cc0000/ffffff"},
        {"title":"Cardify","content":"Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.","id":"3e65ed43-1ca9-4de9-a90f-7815f96b0cec","author":"Elinore","timestamp":"12:26 PM","imageUrl":"http://dummyimage.com/165x138.png/5fa2dd/ffffff"},
        {"title":"Job","content":"Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus.","id":"90845f0b-0b35-47ce-b540-dd60b3e00eb6","author":"Cathrine","timestamp":"11:34 AM","imageUrl":"http://dummyimage.com/148x145.png/ff4444/ffffff"},
        {"title":"Mat Lam Tam","content":"Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat.","id":"98492abd-5e09-469e-9cf2-b53218427b93","author":"Edgardo","timestamp":"3:25 PM","imageUrl":"http://dummyimage.com/217x189.bmp/dddddd/000000"},
        {"title":"Rank","content":"Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti.","id":"ccb5934c-6280-4bf5-9170-dfcec4c059ff","author":"Fransisco","timestamp":"2:00 AM","imageUrl":"http://dummyimage.com/104x158.png/cc0000/ffffff"},
        {"title":"Transcof","content":"Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio.","id":"c8a01bf7-1f30-4599-bb1b-25abcdb631e7","author":"Cull","timestamp":"6:56 AM","imageUrl":"http://dummyimage.com/120x113.bmp/cc0000/ffffff"},
        {"title":"Overhold","content":"Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy.","id":"ab66df97-e633-4e52-b2b6-3803d0e42855","author":"Ediva","timestamp":"6:07 PM","imageUrl":"http://dummyimage.com/198x163.jpg/dddddd/000000"},
        {"title":"Job","content":"Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.","id":"c7ac06ca-3f8e-49f4-af74-221a1f3ac1ac","author":"Reggi","timestamp":"4:20 PM","imageUrl":"http://dummyimage.com/163x128.png/ff4444/ffffff"},
        {"title":"Voltsillam","content":"Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst.","id":"eff2f6b4-72cb-4e8c-9982-ab1150c53348","author":"Kevina","timestamp":"2:33 PM","imageUrl":"http://dummyimage.com/157x127.png/dddddd/000000"},
        {"title":"Fintone","content":"Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem.","id":"9c68081d-edc9-45f4-bf7c-61ab9893f791","author":"Jewel","timestamp":"4:58 AM","imageUrl":"http://dummyimage.com/228x234.jpg/cc0000/ffffff"},
        {"title":"Bamity","content":"Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.","id":"12368279-3f8f-48e0-9c73-fbe7e18e8f49","author":"Igor","timestamp":"3:16 AM","imageUrl":"http://dummyimage.com/242x202.png/cc0000/ffffff"},
        {"title":"Fixflex","content":"Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum.","id":"9cf93aaa-af4e-4f82-a167-5d117fd6d43f","author":"Mitchel","timestamp":"1:50 AM","imageUrl":"http://dummyimage.com/159x241.jpg/5fa2dd/ffffff"},
        {"title":"Quo Lux","content":"Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum.","id":"a40d83df-3b4f-417d-964c-4f0ec706aec7","author":"Nadean","timestamp":"3:20 AM","imageUrl":"http://dummyimage.com/216x198.png/ff4444/ffffff"},
        {"title":"Bamity","content":"Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.","id":"84685285-7a30-463e-b75e-92478dd0fee9","author":"Tori","timestamp":"6:12 PM","imageUrl":"http://dummyimage.com/182x157.bmp/ff4444/ffffff"},
        {"title":"Bamity","content":"Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat.","id":"2e32668c-7959-49b8-a6d0-6970c94d6025","author":"Hamish","timestamp":"11:51 PM","imageUrl":"http://dummyimage.com/222x233.png/5fa2dd/ffffff"},
        {"title":"Konklux","content":"Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi.","id":"8fa22c02-d26d-4173-9c72-000c17e08883","author":"Vere","timestamp":"5:32 PM","imageUrl":"http://dummyimage.com/176x209.bmp/ff4444/ffffff"},
        {"title":"Subin","content":"Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.","id":"86a9bb60-859f-4913-a6e9-0b96fb50d8eb","author":"Jefferey","timestamp":"4:08 AM","imageUrl":"http://dummyimage.com/242x140.jpg/5fa2dd/ffffff"},
        {"title":"Viva","content":"Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.","id":"ef481a22-8b68-4539-ad11-f0644f3ea8d0","author":"Pippy","timestamp":"4:48 PM","imageUrl":"http://dummyimage.com/185x231.jpg/ff4444/ffffff"},
        {"title":"Konklux","content":"In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis.","id":"2e2409a0-f0e1-43a4-8c8b-991fa629877b","author":"Maud","timestamp":"12:57 AM","imageUrl":"http://dummyimage.com/184x154.bmp/5fa2dd/ffffff"},
        {"title":"Voyatouch","content":"Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor. Duis mattis egestas metus. Aenean fermentum.","id":"61265f0c-030f-482d-9f36-045272f1caa1","author":"Miquela","timestamp":"1:58 PM","imageUrl":"http://dummyimage.com/160x175.jpg/dddddd/000000"},
        {"title":"Overhold","content":"Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque.","id":"7b435647-6a55-4488-b8d7-6223599b2191","author":"Hatty","timestamp":"12:52 PM","imageUrl":"http://dummyimage.com/183x119.bmp/5fa2dd/ffffff"},
        {"title":"Subin","content":"Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.","id":"ee7efc6c-ac81-4861-9025-7deb870ef333","author":"Kellby","timestamp":"10:51 AM","imageUrl":"http://dummyimage.com/205x242.png/5fa2dd/ffffff"},
        {"title":"Tres-Zap","content":"Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.","id":"a5abb736-b10a-468b-901e-f3026f044d02","author":"Culver","timestamp":"6:50 PM","imageUrl":"http://dummyimage.com/182x180.bmp/5fa2dd/ffffff"},
        {"title":"Temp","content":"Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.","id":"be7bc58c-e3c7-40b6-8be5-46dcca213660","author":"Garreth","timestamp":"4:47 AM","imageUrl":"http://dummyimage.com/217x248.png/5fa2dd/ffffff"},
        {"title":"Bitwolf","content":"Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem.","id":"f39e8fec-348b-41bc-baa8-f9bbff562273","author":"Christian","timestamp":"9:17 PM","imageUrl":"http://dummyimage.com/152x138.bmp/dddddd/000000"},
        {"title":"Bigtax","content":"In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit.","id":"9052bc76-1213-4136-bcc2-66b3d3543d6d","author":"Eyde","timestamp":"1:18 PM","imageUrl":"http://dummyimage.com/138x105.bmp/dddddd/000000"},
        {"title":"Alpha","content":"Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus.","id":"d10aa247-42bc-4b97-8a74-c3fa83533eed","author":"Byram","timestamp":"4:18 AM","imageUrl":"http://dummyimage.com/186x201.jpg/5fa2dd/ffffff"},
        {"title":"Alphazap","content":"Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti.","id":"34efb6ca-c582-412c-b350-121ea9783b9e","author":"Norah","timestamp":"6:02 AM","imageUrl":"http://dummyimage.com/134x153.jpg/cc0000/ffffff"}],
        selectedPost:'',
        comments: [{
            author: "admin",
            content: "comment content comment content comment content comment content comment content comment content comment content comment content comment content comment content comment content comment content comment content comment content comment content comment content comment content comment content comment content comment content comment content",
            timestamp: Date.now(),
            upvotes: 5
          },
          {
          author: "admin",
          content:
          "comment content comment content comment content comment content comment content comment content comment content comment content comment content comment content comment content comment content comment content comment content comment content comment content comment content comment content comment content comment content comment content",
          timestamp: Date.now(),
          upvotes: 3
        }]
    },
    mutations:{
        changeActivePost(state, payload){
            state.selectedPost = payload;
        }
    },
    getters:{
        blogPosts: state => {
            return state.blogPosts
        },
        selectedPost: state => {
            return state.selectedPost
        },
        comments: state => {
            return state.comments
        }
    }
});

